---
# copyright Utrecht University
# This playbook deploys a complete COmanage install.

- hosts: all
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full | version_compare('2.4', '>=')"
        msg: >
          "You must update Ansible to at least 2.4 to deploy Yoda."


- name: Provision ldap server
  hosts: ldaps
  become: yes
  roles:
    - ldap
    - federated-authentication
  tags:
    - ldap


- name: Provision comanage server
  hosts: comanages
  become: yes
  roles:
    - { role: certificates, tags: [ 'comanage', 'database' ] }
    - apache
    - php
    - postgresql
    - comanage
  tags:
    - comanage
