---
# copyright Utrecht University

# iRODS configuration.
irods_service_account: irods
irods_zone: tempZone                       # The name of the iRODS Zone

# Test configuration.
test_password: test

test_users:
  - name: researcher
    password: '{{ test_password }}'
    type: rodsuser
  - name: viewer
    password: '{{ test_password }}'
    type: rodsuser
  - name: groupmanager
    password: '{{ test_password }}'
    type: rodsuser
  - name: datamanager
    password: '{{ test_password }}'
    type: rodsuser
  - name: functionaladmingroup
    password: '{{ test_password }}'
    type: rodsuser
  - name: functionaladmincategory
    password: '{{ test_password }}'
    type: rodsuser
  - name: functionaladminpriv
    password: '{{ test_password }}'
    type: rodsuser
  - name: technicaladmin
    password: '{{ test_password }}'
    type: rodsadmin
  - name: testuseradd
    password: '{{ test_password }}'
    type: rodsuser
  - name: testuserdel
    password: '{{ test_password }}'
    type: rodsuser

test_groups:
  - groupName: research-initial
    category: initial
    subcategory: initial
  - groupName: datamanager-initial
    category: initial
    subcategory: initial
  - groupName: grp-intake-initial
    category: intake-intake
    subcategory: intake-intake
  - groupName: grp-datamanager-initial
    category: intake-intake
    subcategory: intake-intake
  - groupName: grp-vault-initial
    category: intake-intake
    subcategory: intake-intake
  - groupName: grp-intake-test
    category: intake-intake
    subcategory: intake-intake
  - groupName: grp-datamanager-test
    category: intake-intake
    subcategory: intake-intake
  - groupName: grp-vault-test
    category: intake-intake
    subcategory: intake-intake
  - groupName: research-deletegroup
    category: initial
    subcategory: initial
  - groupName: research-updateproperties
    category: initial
    subcategory: initial
  - groupName: research-mdtest
    category: initial
    subcategory: initial
  - groupName: research-process1
    category: initial
    subcategory: initial
  - groupName: research-process2
    category: initial
    subcategory: initial
  - groupName: research-process3
    category: initial
    subcategory: initial
  - groupName: research-revisions
    category: initial
    subcategory: initial
  - groupName: research-search
    category: initial
    subcategory: initial

test_groupusers:
  - groupName: priv-category-add
    user: functionaladminpriv
    role: manager
  - groupName: priv-category-add
    user: functionaladmincategory
    role: manager
  - groupName: priv-group-add
    user: functionaladminpriv
    role: manager
  - groupName: priv-group-add
    user: functionaladmingroup
    role: manager
  - groupName: research-initial
    user: functionaladminpriv
    role: manager
  - groupName: research-initial
    user: groupmanager
    role: manager
  - groupName: research-initial
    user: researcher
    role: normal
  - groupName: research-initial
    user: viewer
    role: reader
  - groupName: research-initial
    user: testuserdel
    role: normal
  - groupName: datamanager-initial
    user: functionaladminpriv
    role: manager
  - groupName: datamanager-initial
    user: datamanager
    role: normal
  - groupName: research-deletegroup
    user: functionaladminpriv
    role: manager
  - groupName: research-deletegroup
    user: groupmanager
    role: manager
  - groupName: research-deletegroup
    user: datamanager
    role: normal
  - groupName: grp-intake-initial
    user: researcher
    role: normal
  - groupName: grp-intake-initial
    user: groupmanager
    role: manager
  - groupName: grp-intake-initial
    user: datamanager
    role: normal
  - groupName: grp-datamanager-initial
    user: datamanager
    role: manager
  - groupName: grp-intake-test
    user: researcher
    role: normal
  - groupName: grp-intake-test
    user: groupmanager
    role: manager
  - groupName: grp-intake-test
    user: datamanager
    role: normal
  - groupName: grp-datamanager-test
    user: datamanager
    role: manager
  - groupName: research-deletegroup
    user: viewer
    role: reader
  - groupName: research-updateproperties
    user: functionaladminpriv
    role: manager
  - groupName: research-updateproperties
    user: groupmanager
    role: manager
  - groupName: research-updateproperties
    user: researcher
    role: normal
  - groupName: research-updateproperties
    user: viewer
    role: reader
  - groupName: research-mdtest
    user: functionaladminpriv
    role: manager
  - groupName: research-mdtest
    user: groupmanager
    role: manager
  - groupName: research-mdtest
    user: researcher
    role: normal
  - groupName: research-mdtest
    user: viewer
    role: reader
  - groupName: research-process1
    user: functionaladminpriv
    role: manager
  - groupName: research-process1
    user: groupmanager
    role: manager
  - groupName: research-process1
    user: researcher
    role: normal
  - groupName: research-process1
    user: viewer
    role: reader
  - groupName: research-process2
    user: functionaladminpriv
    role: manager
  - groupName: research-process2
    user: groupmanager
    role: manager
  - groupName: research-process2
    user: researcher
    role: normal
  - groupName: research-process2
    user: viewer
    role: reader
  - groupName: research-process3
    user: functionaladminpriv
    role: manager
  - groupName: research-process3
    user: groupmanager
    role: manager
  - groupName: research-process3
    user: researcher
    role: normal
  - groupName: research-process3
    user: viewer
    role: reader
  - groupName: research-revisions
    user: functionaladminpriv
    role: manager
  - groupName: research-revisions
    user: groupmanager
    role: manager
  - groupName: research-revisions
    user: researcher
    role: normal
  - groupName: research-revisions
    user: viewer
    role: reader
  - groupName: research-search
    user: functionaladminpriv
    role: manager
  - groupName: research-search
    user: groupmanager
    role: manager
  - groupName: research-search
    user: researcher
    role: normal
  - groupName: research-search
    user: viewer
    role: reader
